# Design Philosophy:
# - Lazy to debug formatting
# - Lazy to test colors
# - Easier to just use an existing color scheme and design
#
# Catppuccin Color:
# - text : whitest white text
# - surface0 : blackest black surface
# - crust : blackest black test
# 
# To install:
# wget https://raw.githubusercontent.com/cardin/starship/refs/heads/mod/docs/public/presets/toml/catppuccin-powerline.toml -O $STARSHIP_CONFIG

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
[](bg:red fg:prev_bg)\
$username\
$hostname\
[](bg:peach fg:prev_bg)\
$directory\
[](bg:yellow fg:prev_bg)\
$git_branch\
$git_commit\
$git_status\
[](fg:prev_bg bg:green)\
$nodejs\
$java\
$python\
[](fg:prev_bg bg:sapphire)\
$docker_context\
$conda\
[](fg:prev_bg bg:lavender)\
$jobs\
$memory_usage\
[](fg:prev_bg bg:surface0)\
$time\
$cmd_duration\
[ ](fg:prev_bg)\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:prev_bg fg:prev_bg"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "[](fg:blue bg:prev_fg)"
Ubuntu = "[](fg:peach bg:prev_fg)"

[username]
show_always = true
style_user = "bg:prev_bg fg:crust"
style_root = "bg:prev_bg fg:bold #FFFFFF"
format = '[ $user ]($style)'

[hostname]
# by default only shows on SSH
ssh_symbol = ""
style = "fg:prev_fg bg:prev_bg"
format = "[$ssh_symbol $hostname ]($style)"

[directory]
style = "bg:prev_bg fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only_style = "fg:color_red bg:prev_bg"
read_only = "󰌾 "

# fg redefined for all modules below, as they're optional and prev module may not exist
[git_branch]
symbol = ""
style = "fg:crust bg:prev_bg"
format = '[ $symbol $branch ]($style)'

[git_commit]
style = "fg:crust bg:prev_bg"
format = "[($tag)]($style)"

[git_status]
style = "fg:crust bg:prev_bg"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:crust bg:prev_bg"
format = '[ $symbol( $version) ]($style)'
version_format = "${major}"

[java]
symbol = " "
style = "fg:crust bg:prev_bg"
format = '[ $symbol( $version) ]($style)'
version_format = "${major}"

[python]
symbol = ""
style = "fg:crust bg:prev_bg"
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'
version_format = '${major}.${minor}'

[docker_context]
symbol = ""
style = "fg:crust bg:prev_bg"
format = '[ $symbol( $context) ]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:prev_bg"
format = '[$symbol$environment ]($style)'
ignore_base = false

[jobs]
symbol = "󰆅"
style = "fg:crust bg:prev_bg"
format = "[ $symbol( $number)]($style)"

[memory_usage]
symbol = "󰍛"
style = "fg:bold red bg:prev_bg"
format = "[ $symbol ${ram} ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:subtext1 bg:prev_bg"
format = '[  $time ]($style)'

[cmd_duration]
format = "[ $duration ]($style)"
style = "fg:prev_fg bg:prev_bg"

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
