# Design Philosophy:
# - Lazy to debug formatting
# - Lazy to test colors
# - Easier to just use an existing color scheme and design
#
# To install:
# wget https://raw.githubusercontent.com/cardin/starship/refs/heads/mod/docs/public/presets/toml/gruvbox-rainbow.toml -O $STARSHIP_CONFIG

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$os\
[](fg:prev_fg bg:color_orange)\
$username\
$hostname\
[](fg:prev_bg bg:color_yellow)\
$directory\
[](fg:prev_bg bg:color_aqua)\
$git_branch\
$git_commit\
$git_status\
[](fg:prev_bg bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:prev_bg bg:color_bg3)\
$docker_context\
$conda\
$jobs\
[](fg:prev_bg bg:color_bg1)\
$time\
$cmd_duration\
$memory_usage\
[ ](fg:prev_bg)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:prev_bg fg:prev_bg"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "[](fg:blue bg:prev_fg)"
Ubuntu = "[](fg:yellow bg:prev_fg)"
SUSE = "[](fg:green bg:prev_fg)"
Raspbian = "[󰐿](fg:red bg:prev_fg)"
Mint = "[󰣭](fg:green bg:prev_fg)"
Macos = "[󰀵](fg:white bg:prev_fg)"
Manjaro = "[](fg:green bg:prev_fg)"
Linux = "[󰌽](fg:white bg:prev_fg)"
Gentoo = "[󰣨](fg:white bg:prev_fg)"
Fedora = "[󰣛](fg:red bg:prev_fg)"
Alpine = "[](fg:cyan bg:prev_fg)"
Amazon = "[](fg:yellow bg:prev_fg)"
Android = "[](fg:green bg:prev_fg)"
Arch = "[󰣇](fg:blue bg:prev_fg)"
Artix = "[󰣇](fg:blue bg:prev_fg)"
EndeavourOS = "[](fg:purple bg:prev_fg)"
CentOS = "[](fg:blue bg:prev_fg)"
Debian = "[󰣚](fg:red bg:prev_fg)"
Redhat = "[󱄛](fg:red bg:prev_fg)"
RedHatEnterprise = "[󱄛](fg:red bg:prev_fg)"
Pop = "[](fg:cyan bg:prev_fg)"

[username]
# by default only shows on SSH
style_user = "bg:prev_bg fg:color_fg0"
style_root = "bg:prev_bg fg:color_fg0"
format = '[  $user ]($style)'

[hostname]
# by default only shows on SSH
ssh_symbol = ""
style = "fg:prev_fg bg:prev_bg"
format = "[$ssh_symbol $hostname ]($style)"

[directory]
style = "fg:color_fg0 bg:prev_bg"
read_only_style = "fg:color_red bg:prev_bg"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = "󰌾 "

[git_branch]
symbol = ""
style = "fg:color_fg0 bg:prev_bg"
format = '[ $symbol $branch ]($style)'

[git_commit]
style = "fg:prev_fg bg:prev_bg"
format = "[($tag)]($style) "	

[git_status]
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ](fg:color_fg0 bg:prev_bg)' # bug, must set explicitly

[c]
symbol = " "
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $version)( $virtualenv) ]($style)' 

[docker_context]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $context) ]($style)'

[conda]
symbol = ""
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = '[ $symbol( $environment) ]($style)'

[jobs]
symbol = "󰆅"
style = "fg:color_fg0 bg:prev_bg" # fg redefined, as prev module may not exist
format = "[ $symbol( $number) ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:color_fg0 bg:prev_bg"
format = '[  $time ]($style)'

[cmd_duration]
style = "fg:prev_fg bg:prev_bg"
format = "[ $duration ]($style)"

[memory_usage]
symbol = "󰍛"
style = "fg:bold color_red bg:prev_bg"
format = "[$symbol ${ram} ]($style)"
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
