"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
$hostname\
$localip\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$nodejs\
$java\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$jobs\
[](fg:color_bg3 bg:color_bg1)\
$time\
$cmd_duration\
[ ](fg:color_bg1)\
$memory_usage\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fdf7df'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"
format = "[$symbol ]($style)"

[os.symbols]
Windows = ""
Ubuntu = ""
Alpine = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
# by default only shows on SSH
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:bold color_red"
format = '[$user ]($style)'

[hostname]
# by default only shows on SSH
ssh_symbol = "󰢩"
style = "bg:color_orange fg:color_fg0"
format = "[$ssh_symbol $hostname ]($style)"

[localip]
# by default only shows on SSH. Continuation of hostname
disabled = false
style = "bg:color_orange fg:color_fg0"
format = "[󱦂 $localipv4 ]($style)"

[directory]
style = "fg:color_fg0 bg:color_yellow"
read_only_style = "fg:color_red bg:color_yellow"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰌾 "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"/mnt/c" = "C: "
"/mnt/d" = "D: "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
version_format = "${major}"

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
version_format = "${major}"

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
version_format = "${major}.${minor}"

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[jobs]
symbol = "󰆅"
style = "bg:color_bg3"
format = "[[ $symbol( $number) ](fg:#83a598 bg:color_bg3)]($style)"
number_threshold = 1

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[cmd_duration]
style = "bg:color_bg1"
format = "[[  $duration ](fg:color_fg0 bg:color_bg1)]($style)"
min_time = 1000

[memory_usage]
symbol = "󰍛"
format = "[$symbol ${ram}( 󰾵 ${swap})](bold color_red) "
disabled = false

[character]
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
